site_name: Farming Games Help
site_url: https://farminggames.help
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
nav:
  - Home: index.md
  - Beginner Guides:
      - '🌟【星露谷物语】纯新手向攻略（第二期）——春季前期钓鱼篇': guides/星露谷物语纯新手向攻略第二期春季前期钓鱼篇.md
  - Guides: guides.md
  - About: about.md